### ISSUE TITLE
Wurst will not load on linux.

### ISSUE THREAD

**Issue by GlitchHead** [Wurst-Imperium/Wurst-Client#57]
I have currently using linux Kali Linux and Wurst will not start on it im stuck at the Wurst Loading screen... here is the logs and information needed:

This is the Lancher logs:
http://pastebin.com/zT5BaS1J

Here is the Game output then i click "Play"
http://pastebin.com/aHfjatjx

And The Lancher Log after play:
http://pastebin.com/9chjJU0R

Its stays like that untill i close Minecraft Wurst (The game output)
when i do i get:
[15:19:40] [Client Shutdown Thread/INFO]: Stopping server
AL lib: (EE) alc_cleanup: 1 device not closed
(game output)

Version of Wurst:
Wurst-Client-v1.5

The Minecraft lancher is the latest version and works with Minecraft 1.8 not the wurst client.

java version:
java version "1.6.0_34"
OpenJDK Runtime Environment (IcedTea6 1.13.6) (6b34-1.13.6-1~deb7u1)
OpenJDK Server VM (build 23.25-b01, mixed mode)

**Comment by Alexander01998** [comment]
Try updating to Java 8.

**Comment by GlitchHead** [comment]
i updated to java 8 and no change still is stuck on wurst loading screen... :C

**Comment by GlitchHead** [comment]
Im planning on changing my computer to kali linux because my windows computer is highly fucked up
so im testing stuff and Wurst does not work.

**Comment by Alexander01998** [comment]
> i updated to java 8 and no change still is stuck on wurst loading screen... :C

I'm currently getting the same error when trying to compile Wurst v1.5.1.

It's caused by the MCP reobfuscator and I think I just managed to bypass it.

**Comment by GlitchHead** [comment]
yea! i think thats good!

**Comment by Alexander01998** [comment]
Fun-fact: `bug.class` is causing this bug.

**Comment by GlitchHead** [comment]
:D

**Comment by Alexander01998** [comment]
> Im planning on changing my computer to kali linux because my windows computer is highly fucked up
> so im testing stuff and Wurst does not work.

Try RedHat Linux. It keeps running even when the hard disks break.

[![YouTube video](https://i.ytimg.com/vi_webp/5KEhhW8TOGk/mqdefault.webp)](https://www.youtube.com/watch?v=5KEhhW8TOGk)

**Comment by Alexander01998** [comment]
Fixed it! Give me a minute to release it...

![screenshot](https://cloud.githubusercontent.com/assets/10100202/6316201/b4cc7ff4-ba1e-11e4-960d-ecb4ccd7f7c8.png)

**Comment by GlitchHead** [comment]
k

**Comment by GlitchHead** [comment]
tryed 1.5.1 and now WURST is crashing when it starts crash report:
http://pastebin.com/7DRg1Rx0

**Comment by Alexander01998** [comment]
It's trying to load a custom AutoBuild template that has errors (it's using `?`s instead of `§`s).

**Comment by GlitchHead** [comment]
well i edited the autobuild template and replaced the ? s with § and im still getting error :c

**Comment by Alexander01998** [comment]
Same crash report?

**Comment by GlitchHead** [comment]
yes

**Comment by GlitchHead** [comment]
should i post it again?

**Comment by Alexander01998** [comment]
Jup.

**Comment by GlitchHead** [comment]
Crash:
http://pastebin.com/M1QTQ15h

AutoBuild:
WARNING! This is complicated!

How to make a custom structure for AutoBuild:
There are two types of structures: simple structures and advanced structures.
The difference is that advanced strcutures place blocks in certain directions,
while simple structures use the direction that you placed the first block in
for all their blocks. To make your structure, you need to add a line for every
block. In a simple structure, these lines look like this:
0§0§0
The first number determines how far the block is moved to the right or left. 0 is
where you placed the first
block, 1 is one block further on the left and -1 is one block further on the right.
The second number determines how far the block is moved up or down. 0 is where you placed
the first block, 1 is one block above and -1 is one block below.
The third number determines how far the block is moved to the front/rear.
0 is where you placed the first block, 1 is one block further away from you
and -1 is one block closer to you.
All simple structures have to start with 0§0§0. This will place the first block where you
clicked.
In an advanced structure, the lines look like this:
0§1§0§2
The first value and the third value work the same way they work in simple structures.
For the second value, 1 is where you placed the first block, 2 is above and 0 is below.
The fourth value determines the direction the block will be placed in.
0 = bottom, 1 = top, 2 = front, 3 = back, 4 = right, 5 = left
In the above example (0§1§0§2), a block is placed in front of the first block you placed.
The first value is 0, the second one is 1 and the third one is 0, meaning it will be placed
on the first block you placed.
The fourth value is 2 (front), meaning it will be placed against the front face of the first
block you placed. So in the end, it will be placed in front of that block.
It's like clicking on the front face of that block.
Advanced structures do NOT start by placing the first block where you clicked.

Tips:
-Do not mix simple and advanced structures. Only choose one.
-Your structure should not contain more than 64 blocks and should not be bigger than 8x8x8.
-Make sure you don't try to place blocks against air blocks. That will only work in
 Singleplayer.

Example for a simple structure (pillar):
0§0§0
0§1§0
0§2§0
0§3§0
0§4§0
0§5§0
0§6§0

Example for an advanced structure (swastika):
0§1§0§5
1§1§0§5
0§1§0§1
0§2§0§1
0§3§0§5
0§3§0§4
1§3§0§5
-1§3§0§4
-2§3§0§0
-2§2§0§0
0§3§0§1
2§3§0§1
2§4§0§1
0§4§0§1
0§5§0§4
-1§5§0§4

Make your own structure here:
0§1§0§4
0§1§0§5
-1§1§0§4
1§1§0§5
-2§1§0§4
2§1§0§5
-1§1§0§1
1§1§0§1
-2§1§0§1
2§1§0§1
-1§2§0§1
1§2§0§1
1§3§0§4
0§3§0§1

**Comment by GlitchHead** [comment]
it was first ? and i replaced all ? s with §

**Comment by GlitchHead** [comment]
any ideas?

**Comment by GlitchHead** [comment]
if i delete autobuild_custom.txt and start mc wurst it creates a new one with ? s

**Comment by GlitchHead** [comment]
also if your getting a bit confused on the autobuild custom thing i posted i tryed to copy autobuild_custom.txt from the windows .minecraft it was the illumati object thing thats why this is different.

**Comment by GlitchHead** [comment]
OMFG I GOT IT YAYAYAYAYAYAYA i replaced in auto build custom.txt the stuff paste your own object here thing with 0

**Comment by GlitchHead** [comment]
wow the auto maximize worked on linux
i dont thing wurst has ever been tested on linux... some stuff is a bit weird
![2015-02-21_19 36 03](https://cloud.githubusercontent.com/assets/8052644/6316777/cf56bffe-ba2a-11e4-810f-dd5d8efe32ff.png)

**Comment by GlitchHead** [comment]
also thats my skin its not glitched or anything. yes my skin has nothing on it.

**Comment by GlitchHead** [comment]
The alts act weird also i think linux or something just does not like § at all.
please update everything to json soon and remove § thx

**Comment by Alexander01998** [comment]
> The alts act weird also i think linux or something just does not like § at all.
> please update everything to json soon and remove § thx

See #51.

> it was first ? and i replaced all ? s with §
> and im still getting crash

I guess Linux uses a different encoding that can't handle `§` properly. Try changing the encoding to `Windows 1252`.

**Comment by GlitchHead** [comment]
Alright i changed my encoding to en_us.utf-8 this supports § now i can save § to text files on linux and stuff but now... instead of 0?1?0?4 i get 0�1�0�4 the § thing is in the autobuild_custom.txt just now wurst wont read it. any ideas?

**Comment by Alexander01998** [comment]
> Alright i changed my encoding to en_us.utf-8 this supports §

Did you try `Windows 1252`?

**Comment by GlitchHead** [comment]
WTF now suddenly its working like really no joke it is magicly working? the alts list is fixed and it wont crash autobuild works too. here is what i think was happening i was putting stuff from my windows computer which was not utf 8 it was Windows 1252 format by having wurst make the shit (i deleted alts.txt and auto build) so wurst made new ones which seem to be utf 8 so i think i did it.

**Comment by GlitchHead** [comment]
my theory was correct i pasted the alts.wurst from my windows computer into http://www.motobit.com/util/charset-codepage-conversion.asp and selected Windows 1252 and converted it to utf 8 and downloaded the new alts.wurst and it worked the alt manager was normal.
